version: '3'

networks:
  backend:
  network:

services:
  db:
    image: postgres:16.2-alpine
    container_name: shop_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
      - TZ=UTC
    ports:
      - '5432:5432'
    volumes: 
      - ./db/postgresql:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: ./shop_online_be
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=

      - FRONTEND_HOST=
      - NAME_SHOP=
      - EMAIL_SHOP=
      - CC_GMAIL_SHOP=

      - GHTK_API_KEY=
      - GHTK_URL=https://services-staging.ghtklab.com
      - GHTK_PICK_NAME=
      - GHTK_PICK_TEL=
      - GHTK_PICK_PROVINCE=
      - GHTK_PICK_DISTRICT=
      - GHTK_PICK_WARD=
      - GHTK_PICK_ADDRESS=
      
    networks:
      - backend
      - network

  nginx:
    build:
      context: ./shop_online_fe
      dockerfile: Dockerfile
      args:
        - REACT_APP_SERVER_HOST=http://localhost:8080/api/v1
        - REACT_APP_ADDRESS_URL=https://esgoo.net/api-tinhthanh/

    container_name: customer_frontend
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - network

 
