export const statusData = [
    {value: null,label:'Tất cả'},
    { value: "-1", label: 'Hủy đơn hàng' },
    { value: "1", label: 'Chưa tiếp nhận' },
    { value: "2", label: 'Đã tiếp nhận' },
    { value: "3", label: 'Đã lấy hàng/Đã nhập kho' },
    { value: "4", label: 'Đã điều phối giao hàng/Đang giao hàng' },
    { value: "5", label: 'Đã giao hàng/Chưa đối soát' },
    { value: "6", label: 'Đã đối soát' },
    { value: "7", label: 'Không lấy được hàng' },
    { value: "8", label: 'Hoãn lấy hàng' },
    { value: "9", label: 'Không giao được hàng' },
    { value: "10", label: 'Delay giao hàng' },
    { value: "11", label: 'Đã đối soát công nợ trả hàng' },
    { value: "12", label: 'Đã điều phối lấy hàng/Đang lấy hàng' },
    { value: "13", label: 'Đơn hàng bồi hoàn' },
    { value: "20", label: 'Đang trả hàng (COD cầm hàng đi trả)' },
    { value: "21", label: 'Đã trả hàng (COD đã trả xong hàng)' },
    { value: "123", label: 'Shipper báo đã lấy hàng' },
    { value: "127", label: 'Shipper (nhân viên lấy/giao hàng) báo không lấy được hàng' },
    { value: "128", label: 'Shipper báo delay lấy hàng' },
    { value: "45", label: 'Shipper báo đã giao hàng' },
    { value: "49", label: 'Shipper báo không giao được giao hàng' },
    { value: "410", label: 'Shipper báo delay giao hàng' }
]